// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SindyPetshop.Infrastructure.Data;

#nullable disable

namespace SindyPetshop.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SindyPetshopDbContext))]
    [Migration("20260727195422_AddMascotaYTrazabilidadCompras")]
    partial class AddMascotaYTrazabilidadCompras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MascotaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VarianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VarianteId");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.HistorialStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VarianteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VarianteId");

                    b.ToTable("HistorialStock");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoEntrega")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DireccionId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.VarianteProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Atributo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CantidadFraccionable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsFraccionable")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockFisico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockMinimoWeb")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VarianteDestinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VarianteDestinoId");

                    b.ToTable("VariantesProducto");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.DetallePedido", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Mascota", "Mascota")
                        .WithMany("ComprasAsociadas")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindyPetshop.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindyPetshop.Domain.Entities.VarianteProducto", "Variante")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Pedido");

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.HistorialStock", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.VarianteProducto", "Variante")
                        .WithMany("Movimientos")
                        .HasForeignKey("VarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variante");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Mascota", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Mascotas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindyPetshop.Domain.Entities.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.VarianteProducto", b =>
                {
                    b.HasOne("SindyPetshop.Domain.Entities.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindyPetshop.Domain.Entities.VarianteProducto", "VarianteDestino")
                        .WithMany()
                        .HasForeignKey("VarianteDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Producto");

                    b.Navigation("VarianteDestino");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Mascotas");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Mascota", b =>
                {
                    b.Navigation("ComprasAsociadas");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("SindyPetshop.Domain.Entities.VarianteProducto", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
